import type { SectionData, ThemeData } from "./types";

export const FESTIVE_AIR_SECTIONS: SectionData[] = [
  {
    id: "hero-1",
    type: "hero",
    visible: true,
    order: 0,
    content: {
      title: "Happy Birthday,",
      subtitle: "Beautiful!",
      titleAlignment: "center",
      height: "full",
      backgroundOverlay: 30,
      overlayColor: "#874e58",
      ctaText: "Celebrate",
      ctaLink: "#our-story",
      backgroundImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCG6bUEIpQmK2f7iQ8KkxWVfli2qeXci8d7UQA743QfFzZF9WzYg_tP2EWpR7gDaxwxK3ebxI63ALFAwU_amqmW9V6-cP5SVKA3Sly3gN98ntQb66s7L4rI_nRq9XhgjwveGZx0WDMvtMWpL1Nkph5aTjcepHHGofP9687wThKfPJXTp4WVf4uFp7N5NDGfMQahUoMc0lFQOWq-76g5fQ4UWDXYX4Gu9tMEMuWyYlrLWuTE6s-xI0IXNDwUGPxTA-z_R-A2ruV8wiLN",
    },
    settings: {},
  },
  {
    id: "quote-1",
    type: "quote",
    visible: true,
    order: 1,
    content: {
      text: "Life is a beautiful journey, and every year with you makes the view even more breathtaking.",
      style: "inline",
      backgroundStyle: "solid",
    },
    settings: {},
  },
  {
    id: "timeline-1",
    type: "timeline",
    visible: true,
    order: 2,
    content: {
      heading: "Our Journey",
      events: [
        { id: "e1", date: "2020-01-15", title: "The First Hello", description: "That coffee shop by the corner where we talked for hours until they had to close. I knew right then this was something special.", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAZYrG0GqLKLvDdBTZ--FgM20qtJqTirlJb0-mGQm2-nt8psOCKTi0xnRq2MI9rwcUossMXtY3ZS_FKQt9p3sRw6qLuCgKqU8IRsvuAU0AsiR1R8f88P0boDxBPL3CIYXTgPTJ-AkmVlTa-NmILMEFcWsv58Mb7mOK7krkMl1HS-dud-kJE0gjQ5wu4yQ41n5nwpSYJj3LLGcd9t9vttWYmO40huuv5X_Q3CoEI0RhPH6W7Sfa182vXX1CxaoCQK1KaewWx96e-Gwat" },
        { id: "e2", date: "2020-06-20", title: "Our First Trip", description: "Getting lost in the city streets, finding that hidden bakery, and laughing until our sides hurt. The world felt like it was just ours.", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBdbI2eG9kh0_MjBLUs1ZVIWKwL1BaZeW69ga2_j7jW72ljrGe-Fd6n7SFtQauL1p1LWfcC9OyDu1m3ipylYksXzOymFf9SIMOYEhLCy2NS8Qaa245OHBtBv7kNPnztzLFxqeGkWrn4U-7i9tXgfWu5V8kZn-jPzixcv1u8zdv9tryKL42qdf5GjDfM7uebjTHqa0FmCl8DR9Y8ZrOi6_Pn6tIsVsNjicAQn7RklCEXdxFKuxdTijMVTXetyukcJZP5MrPzeTuNpXE_" },
        { id: "e3", date: "2024-12-25", title: "Today", description: "Celebrating you, the most amazing person I know. And this is just the beautiful beginning of our next chapter together.", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDqIJnSbGeR4EE2N7Y-AmEfVOMLOjsRLgd0yqV4Pr-1r1DP6jLug4A_XDj6RZFwDJcQtst8zgN8wor_Yc09oy79jd2YcZLa0BeO6WEC5gK7fjk-UDhhbMga5bsZl9zlexoex_QFdaP7V_Mg3VTEP8lkRGbeOBqSIYf1ov_6QyFawgbsD3Hg9y1_K2qRX4VGv1gNAIFaICXAELtCS3URH7GnFt4UbS-oGiNtwsZdQ-Pd1WpCw9UZS6boz2NR8QolNarsUIP4-uYQEqH9" },
      ],
      style: "alternating",
      showDates: true,
      showImages: true,
    },
    settings: {},
  },
  {
    id: "countdown-1",
    type: "countdown",
    visible: true,
    order: 3,
    content: {
      title: "We can't wait to celebrate you!",
      targetDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 14 * 60 * 60 * 1000 + 45 * 60 * 1000 + 22 * 1000).toISOString(),
      expiredMessage: "The moment has arrived!",
      style: "boxes",
      showLabels: true,
    },
    settings: {},
  },
  {
    id: "memory-1",
    type: "memory_highlights",
    visible: true,
    order: 4,
    content: {
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA1n5H3_9Bqni8iTZj8ayTXSpVc9Bf3xPWZWVX9Kkk-ze_bmOvEL4PuAYeeViPdfrkfMx5uLnyi9LOvbxYxDCfkpeveMgJrFinSKhUcrsVQWMtgJ1Y_zRmq97GEJYRsPnjza2e8L16bFTcwuPUyl1Mqcmg0i-Cvw54m0oiYn1jReHgTS6UzuZIWRP1p3fnXlOofgAqJETFKWKhS_WCyPJBWafOaoqfawBaC-jLMSBK7oSNtg2Y_X3NwdtNUbcTXZE4Frr3GGfMKLAnZ",
      heading: "A Year of Beautiful Light",
      body: "This past year has been illuminated by your smile, your warmth, and the incredible way you touch the lives of everyone around you. Here is to the bright light you bring into this world.",
      signoff: "Cheers to many more",
    },
    settings: {},
  },
  {
    id: "gallery-1",
    type: "gallery",
    visible: true,
    order: 5,
    content: {
      images: [
        { id: "g1", storageId: "", src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDcP1ACKksR4PRoqZ58HbdzLnSRieRrgbNw4LAHu0VhOiWaTuQQjGLqFIoH4kA6tO4RoruMpCDoIS7HZDFlCLkQZSSEZzx5_tXuEfDU8j1kp2DQ1ktT3OH_pHUZcuwUfZX7l3byoW5As2-7B6Zmq6MbPD08BUUvLhXmIqq-EWzID7XopR6ixR_6twnYsoBFvI2ub2jJejMFDK2WBV3Lkusxkbj10-clTvRwLubkgNEU8pzrkMcHazEc6J_rNgBjiRjsn11Zvt_6S-zS", alt: "Celebration balloons" },
        { id: "g2", storageId: "", src: "https://lh3.googleusercontent.com/aida-public/AB6AXuAB-ZW3krzJqG6B03-KF5WLBmhC2JtyGXjMLCFw1KJoyGVTMPoqJMNN2bdIyy8X8gNRLvnoMfQJuPfEp0a1Ez3ot3A6zH-hvKTvhPPg7emMFXeMAxDwRokpyfpdXDRfU0RPACzKI6Df-h0RstKgTGvh9eYIorPFTG81AP4eJ-1zdAv2zg1dykGpQ9By6VFhJAFqGyd-ovkDzNBooNdC_zhIMXjADZIfTlRDTwC-9YqP7EBVwKaud_TNCIUCSegNljIwo6shDfzmy0As", alt: "Party lights" },
        { id: "g3", storageId: "", src: "https://lh3.googleusercontent.com/aida-public/AB6AXuD9wFiO6b_X9jrkvBvnFc_HJkvXzS5ZlHLFqUd6n4ZpM7wYrrupKeHGh8orym5yQZHFWWLKVvTLJMrQNdm5ZFDdTPh_2ptQ7lm66yea_TR1BtGKzFGZ9fPxTooHFbWA6ey1xn9MiY_xRzfvb7hbguWj6pbQdeJ9PCV2v2SJOBrSIk3rRtb1xqBH7vbCFS3JEmQkDUByrk93bP-B20vGgEY9TFaBj-zwg4veWwqcaXfLR6xDIbmbwLt7OqvVkMwfgJY2M9VvRy_RAnON", alt: "Birthday cake" },
        { id: "g4", storageId: "", src: "https://lh3.googleusercontent.com/aida-public/AB6AXuCYpJZ6FUR80WwACBIYJbF-3X3u_DK4ZS2N6sDWQGMKw810NTIJMcA8ZqxL5uW4_cYvGBMyuNNsLqD90NLGz_44TWgIrhcJa800UClvx2OraTgohBuFbXxeJLWhLBINJoz4jqAHKQi9yrLdHa-OSIJ1SF48hMho9DmKdh3pn1a7QziR9hykNIdx1l4kHyT0xxZ9_JjVTqKXuf2GKlIvMe_S8PCZXfHncwoF3rLrexR6NBnQkps0SDNmQEeq1-j-cW-UYOG9Z6H8AJmI", alt: "Happy friends" },
        { id: "g5", storageId: "", src: "https://lh3.googleusercontent.com/aida-public/AB6AXuCdSOH6mnv1Ljv6qhXQsYfZ2RWJTIC13R3J8AmpJPHD7SZ4Rr7v5BH1dUfs7_Oz3W1snrkzQY9nofatzcp1mBlQXzvgAaW7PIRU5aJ_e48dcCCz5ldR_iuEzLwUdx6byG_mg8dauHyWUKzfJpqpudHEMQd1C9xv4jlWdMEPbYg84m_uWdPdCgLAS-ig0CtXtWmDEqlxf1ucbQVivfosYRNIj-YcMr6HmEA4lK940T59R4uxgPvf-8WIyyQPFnRKv_zdL4vGDg9KCbaA", alt: "Happy moment" },
      ],
      layout: "grid",
      columns: 3,
      showCaptions: true,
      gap: "16px",
    },
    settings: {},
  },
  {
    id: "love-notes-1",
    type: "love_notes",
    visible: true,
    order: 6,
    content: {
      heading: "Love Notes",
      subtitle: "Messages from those who adore you.",
      notes: [
        { id: "n1", initial: "J", name: "James", message: "Wishing the happiest of birthdays to my favorite person. You deserve the world and more. Love you always!", colorScheme: "secondary" },
        { id: "n2", initial: "S", name: "Sarah", message: "Can't wait to celebrate you tonight! Get ready for the best night ever. Happy birthday gorgeous!", colorScheme: "primary" },
        { id: "n3", initial: "M", name: "Mike", message: "Another year older, another year wiser, and definitely another year more beautiful. Have an amazing day!", colorScheme: "surface" },
        { id: "n4", initial: "C", name: "Chloe", message: "Happy birthday to the most radiant soul! May your year ahead be as bright and beautiful as your smile. Cheers to you!", colorScheme: "primary" },
        { id: "n5", initial: "D", name: "Daniel", message: "To another year of adventures and great memories! Wishing you the best day ever. You're truly one of a kind.", colorScheme: "secondary" },
        { id: "n6", initial: "S", name: "Sophia", message: "Sending you so much love on your special day! You deserve all the happiness in the world. Have a wonderful celebration!", colorScheme: "surface" },
      ],
      ctaText: "Leave a Note",
      ctaLink: "#",
    },
    settings: {},
  },
  {
    id: "audio-1",
    type: "audio",
    visible: true,
    order: 7,
    content: {
      tracks: [],
      playlistTitle: "Our Soundtrack",
      playlistSubtitle: "Songs that tell our story",
      autoplay: false,
      loop: false,
      showPlaylist: true,
      showCoverImage: true,
      showProgressBar: true,
      showPlayer: true,
    },
    settings: {},
  },
];

export const FESTIVE_AIR_THEME: ThemeData = {
  colors: {
    primary: "#874e58",
    secondary: "#765a05",
    background: "#fdf8ff",
    surface: "#ffffff",
    text: "#1c1149",
    textSecondary: "#514345",
    accent: "#ffd87c",
    border: "#f4acb7",
    error: "#ba1a1a",
    success: "#22c55e",
  },
  typography: {
    headingFont: "Epilogue",
    bodyFont: "Plus Jakarta Sans",
    headingWeight: "700",
    bodyWeight: "400",
    baseFontSize: 16,
    lineHeight: 1.6,
    headingScale: 1.25,
  },
  spacing: {
    sectionPadding: "120px",
    containerWidth: "1200px",
    elementGap: "24px",
    cardPadding: "32px",
  },
  borders: {
    radius: "8px",
    cardRadius: "24px",
    buttonRadius: "9999px",
    borderWidth: "1px",
  },
  effects: {
    shadow: "0 4px 20px rgba(244,172,183,0.1)",
    cardShadow: "0 20px 60px rgba(244,172,183,0.25)",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
  },
};
