import type { ThemeData } from "./types";

export const DEFAULT_THEME: ThemeData = {
  colors: {
    primary: "#e11d48",
    secondary: "#be123c",
    background: "#fef2f2",
    surface: "#ffffff",
    text: "#1f2937",
    textSecondary: "#6b7280",
    accent: "#f59e0b",
    border: "#fce7f3",
    error: "#ef4444",
    success: "#22c55e",
  },
  typography: {
    headingFont: "Playfair Display",
    bodyFont: "Inter",
    headingWeight: "700",
    bodyWeight: "400",
    baseFontSize: 16,
    lineHeight: 1.6,
    headingScale: 1.25,
  },
  spacing: {
    sectionPadding: "80px",
    containerWidth: "1200px",
    elementGap: "24px",
    cardPadding: "32px",
  },
  borders: {
    radius: "8px",
    cardRadius: "12px",
    buttonRadius: "8px",
    borderWidth: "1px",
  },
  effects: {
    shadow: "0 1px 3px rgba(0,0,0,0.1)",
    cardShadow: "0 4px 6px rgba(0,0,0,0.1)",
    transition: "all 0.2s ease",
  },
};

export const THEME_PRESETS: Record<string, ThemeData> = {
  "romantic-rose": {
    ...DEFAULT_THEME,
    colors: {
      primary: "#e11d48",
      secondary: "#be123c",
      background: "#fef2f2",
      surface: "#ffffff",
      text: "#1f2937",
      textSecondary: "#6b7280",
      accent: "#f59e0b",
      border: "#fce7f3",
      error: "#ef4444",
      success: "#22c55e",
    },
  },
  "midnight-love": {
    ...DEFAULT_THEME,
    colors: {
      primary: "#c084fc",
      secondary: "#7c3aed",
      background: "#0f172a",
      surface: "#1e293b",
      text: "#f1f5f9",
      textSecondary: "#94a3b8",
      accent: "#fbbf24",
      border: "#334155",
      error: "#f87171",
      success: "#4ade80",
    },
  },
  "garden-romance": {
    ...DEFAULT_THEME,
    colors: {
      primary: "#16a34a",
      secondary: "#15803d",
      background: "#f0fdf4",
      surface: "#ffffff",
      text: "#1a2e05",
      textSecondary: "#6b7280",
      accent: "#ec4899",
      border: "#dcfce7",
      error: "#ef4444",
      success: "#22c55e",
    },
  },
  "classic-elegance": {
    ...DEFAULT_THEME,
    colors: {
      primary: "#171717",
      secondary: "#404040",
      background: "#fafafa",
      surface: "#ffffff",
      text: "#171717",
      textSecondary: "#737373",
      accent: "#ca8a04",
      border: "#e5e5e5",
      error: "#ef4444",
      success: "#22c55e",
    },
  },
  "sunset-passion": {
    ...DEFAULT_THEME,
    colors: {
      primary: "#ea580c",
      secondary: "#dc2626",
      background: "#fff7ed",
      surface: "#ffffff",
      text: "#1c1917",
      textSecondary: "#78716c",
      accent: "#9333ea",
      border: "#fed7aa",
      error: "#ef4444",
      success: "#22c55e",
    },
  },
  "ocean-dreams": {
    ...DEFAULT_THEME,
    colors: {
      primary: "#0891b2",
      secondary: "#0e7490",
      background: "#ecfeff",
      surface: "#ffffff",
      text: "#164e63",
      textSecondary: "#6b7280",
      accent: "#f472b6",
      border: "#a5f3fc",
      error: "#ef4444",
      success: "#22c55e",
    },
  },
};

export function themeToCSSVariables(theme: ThemeData): Record<string, string> {
  return {
    "--color-primary": theme.colors.primary,
    "--color-secondary": theme.colors.secondary,
    "--color-background": theme.colors.background,
    "--color-surface": theme.colors.surface,
    "--color-text": theme.colors.text,
    "--color-text-secondary": theme.colors.textSecondary,
    "--color-accent": theme.colors.accent,
    "--color-border-theme": theme.colors.border,
    "--color-error": theme.colors.error,
    "--color-success": theme.colors.success,
    "--font-heading": `'${theme.typography.headingFont}', serif`,
    "--font-body": `'${theme.typography.bodyFont}', sans-serif`,
    "--font-heading-weight": theme.typography.headingWeight,
    "--font-body-weight": theme.typography.bodyWeight,
    "--font-size-base": `${theme.typography.baseFontSize}px`,
    "--line-height-base": String(theme.typography.lineHeight),
    "--heading-scale": String(theme.typography.headingScale),
    "--section-padding": theme.spacing.sectionPadding,
    "--container-width": theme.spacing.containerWidth,
    "--element-gap": theme.spacing.elementGap,
    "--card-padding": theme.spacing.cardPadding,
    "--radius-theme": theme.borders.radius,
    "--card-radius": theme.borders.cardRadius,
    "--button-radius": theme.borders.buttonRadius,
    "--border-width": theme.borders.borderWidth,
    "--shadow-theme": theme.effects.shadow,
    "--card-shadow": theme.effects.cardShadow,
    "--transition-theme": theme.effects.transition,
  };
}

export const GOOGLE_FONTS = {
  heading: [
    "Playfair Display",
    "Cormorant Garamond",
    "Libre Baskerville",
    "Lora",
    "Merriweather",
    "EB Garamond",
    "Great Vibes",
    "Dancing Script",
    "Pacifico",
    "Satisfy",
  ],
  body: [
    "Inter",
    "Lato",
    "Open Sans",
    "Nunito",
    "Source Sans 3",
    "Roboto",
    "PT Sans",
    "Work Sans",
  ],
};
